import random

one_dp_problems = [
    "70. Climbing Stairs",
    "746. Min Cost Climbing Stairs",
    "198. House Robber",
    "213. House Robber II",
    "5. Longest Palindromic Substring",
    "647. Palindromic Substrings",
    "91. Decode Ways",
    "322. Coin Change",
    "152. Maximum Product Subarray",
    "139. Word Break",
    "300. Longest Increasing Subsequence",
    "416. Partition Equal Subset Sum",
    "120. Triangle",
    "740. Delete and Earn",
    "377. Combination Sum IV",
    "279. Perfect Squares",
    "2369. Check if There is a Valid Partition For The Array",
    "1856. Maximum Subarray Min-Product",
    "983. Minimum Cost For Tickets",
    "343. Integer Break",
    "673. Number of Longest Increasing Subsequence",
    "691. Stickers to Spell Word",
    "1137. N-th Tribonacci Number",
    "1035. Uncrossed Lines",
    "2140. Solving Questions With Brainpower",
    "2466. Count Ways To Build Good Strings",
    "837. New 21 Game",
    "1626. Best Team With No Conflicts",
    "1406. Stone Game III",
    "472. Concatenated Words",
    "1799. Maximize Score After N Operations",
    "1964. Find the Longest Valid Obstacle Course at Each Position",
    "1359. Count All Valid Pickup and Delivery Options",
]
two_dp_problem = [
    "62. Unique Paths",
    "63. Unique Paths II",
    "1143. Longest Common Subsequence",
    "516. Longest Palindromic Subsequence",
    "1049. Last Stone Weight II",
    "309. Best Time to Buy and Sell Stock with Cooldown",
    "518. Coin Change II",
    "494. Target Sum",
    "97. Interleaving String",
    "877. Stone Game",
    "64. Minimum Path Sum",
    "329. Longest Increasing Path in a Matrix",
    "221. Maximal Square",
    "474. Ones and Zeroes",
    "1911. Maximum Alternating Subsequence Sum",
    "115. Distinct Subsequences",
    "72. Edit Distance",
    "1220. Count Vowels Permutation",
    "312. Burst Balloons",
    "1866. Number of Ways to Rearrange Sticks With K Sticks Visible",
    "10. Regular Expression Matching",
    "1140. Stone Game II",
    "926. Flip String to Monotone Increasing",
    "2218. Maximum Value of K Coins From Piles",
    "920. Number of Music Playlists",
    "1639. Number of Ways to Form a Target String Given a Dictionary",
    "879. Profitable Schemes",
    "1547. Minimum Cost to Cut a Stick",
]
print(random.randint(1, 170))
